name: Publish Docker image push

on:
  push:
    branches:
      - none

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login ${{secrets.DOCKER_REGISITER}} -u  ${{secrets.DOCKER_USERNAME}} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: uhub.service.ucloud.cn/imgen-repo/lastjourney:latest
